name: deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Local deploy on Valheim host
    runs-on: [ self-hosted, linux, x64, valheim ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run deploy script
        run: |
          bash -euxo pipefail /home/game_server/bin/deploy_valheim.sh
