name: validate
on: [push, pull_request]
jobs:
  compose-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose config
        run: docker compose config
